apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: draft, Designed, Development, Testing, Production, Deprecated, Retired
  owner: team-a
  system: artist-engagement-portal
#  dependsOn: ['resource:artists-db']
#  apiConsumedBy: ['component:www-artist']
