apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: faturamento
  description: Dominio relacionado com faturamento
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
      
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: web
