apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cross-domain
  title: Cross
  description: Cross
  annotations:
    kode3.tech/tmforum-color: '233 233 233'
  tags:
    - 'tmforum'
spec:
  owner: digitais
