apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: canais
  description: The boxoffice sub-department
spec:
  type: sub-department
  profile:
    displayName: Canais Digitais
    email: canais@example.com
    # Intentional no picture for testing
  parent: infrastructure
  children: [digitais, fisicos]
