apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra department
spec:
  type: department
  profile:
    displayName: Tecnologia
  # Intentional no profile for testing
  parent: acme-corp
  children: [contextos, canais, infra, inteligencia]
  # children: [backstage, boxoffice]
