apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: integration-group
  description: Time de integração
spec:
  type: sub-department
  profile:
    displayName: Integration Squad
    email: canais@example.com
    # Intentional no picture for testing
  parent: infrastructure
  children: []
