apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: web
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Web
    email: web@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: digitais
  children: [team-vitrine, team-checkout, team-pos-vendas, team-area-logada]
